server:
  port: 9000
spring:
  application:
    name: employee-management

  main:
    allow-circular-references: true

  datasource:
    url: jdbc:mysql://localhost:3306/employee_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1834
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

